services:
  redis:
    image: redis:8.0-alpine
    container_name: redis8-single
    restart: always
    ports:
      - "6379:6379"
    # 启动命令：持久化 + 密码 + 关闭保护模式
    command: >
      redis-server
      --requirepass 123456
      --appendonly yes
      --save 60 100
      --protected-mode no
    volumes:
      # 本地挂载持久化数据
      - ./redis-data:/data
    environment:
      TZ: Asia/Shanghai
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge